project:
  type: website
  output-dir: _site

website:
  title: "My Data Science Blog"
  description: "A blog about data science, R, Python, and analytics"
  site-url: "https://DannyMang.github.io/"
  repo-url: "https://github.com/DannyMang/blog"
  repo-actions: [edit, issue]
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - icon: github
        href: "https://github.com/DannyMang"
      - icon: twitter
        href: "https://twitter.com/DannyMang"

  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - section: "Examples"
        contents:
          - href: blog-post-example.qmd
            text: "Data Visualization in R"
          - href: example.qmd
            text: "Quarto Examples"

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
      dark: [cosmo, custom.scss]
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    code-copy: true
    highlight-style: github
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

execute:
  freeze: auto
  echo: true
  warning: false
  message: false

editor: visual

comments:
  giscus:
    repo: DannyMang/blog-comments

