project:
  type: website
  output-dir: _site

website:
  title: "Daniel Ung"
  description: "A blog about data science, R, Python, and analytics"
  site-url: "https://DannyMang.github.io/"
  repo-url: "https://github.com/DannyMang/DannyMang.github.io"
  repo-actions: [edit, issue]
  
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: blogs.qmd
        text: Blogs
    right:
      - icon: github
        href: "https://github.com/DannyMang"
      - icon: twitter
        href: "https://twitter.com/danielung19"
  sidebar:
    style: "floating"
    search: true
    contents:
      - href: index.qmd
        text: "About"
      - href: blogs.qmd
        text: "Blog Posts"
      - section: "Recent Posts"
        contents:
          - href: blogs/blog-post-example.qmd
            text: "Data Visualization with Python"
          - href: blogs/example.qmd
            text: "Quarto Examples"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    code-fold: false
    code-tools: true
    code-copy: true
    highlight-style: github
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
  daemon: false

editor: visual

comments:
  giscus:
    repo: DannyMang/DannyMang.github.io

